### ISSUE TITLE
Internationalization menu

### ISSUE THREAD

**Issue by nttaylor** [redcross/smoke-alarm-portal#10]
Create horizontal menu for rendering page in different languages as described in
https://github.com/OpenTechStrategies/smoke-alarm-portal/issues/4#issuecomment-112402646.
I am thinking: when user clicks a button on the language bar, server will pull content from foo-language.json and re-serve the page, sending the foo-language content to the index.jade template (and also to the thankyou.jade template after form completion).  @trystant, how does that sound?

**Comment by trystant** [comment]
Hey @nttaylor, I was thinking of using John Resig's module and strategy, described [here](http://ejohn.org/blog/a-strategy-for-i18n-and-node/). Any thoughts on one over the other?

**Comment by kfogel** [comment]
Note i18n menu not needed for Friday, and possibly not in phase 1 at all...

**Comment by nttaylor** [comment]
Thank you, @kfogel, for the reminder that this feature will not be needed for a while. @cecilia-donnelly and I were just kicking some ideas around. @trystant, the John Resig strategy seems very well thought out and awesome, while my idea was a quick brainstorm of how I might do something from scratch. Still, does this project call for something so heavy duty? The Resig solution seems geared toward building a truly international website with lots of content for users around the globe. Our site only has two pages of content and (at least for the present) will only be used by people in the United States. I admit my knowledge of it may be incomplete. If it is going to stay small though, I would be tempted to go with a home-grown solution, especially since I could probably knock it out in a day (not counting time spent making verifiably accurate translations, but that will take the same amount of time regardless of the solution).

**Comment by trystant** [comment]
@nttaylor , I decided to go with that strategy because this project is a test run that will, if successful, expand significantly to other parts of the country. So while it's small this phase, it could be larger in phase two based upon feedback. 

Reflecting upon it further, I don't see a need for the full fledged strategy, but I'd rather use a module that's been tested than rolling my own unless there was a specific requirement that necessitated something new.

.02

**Comment by cecilia-donnelly** [comment]
Update!  @nttaylor and I looked at this and we think that the best thing to do is to use the i18n-2 module (see [here](https://www.npmjs.com/package/i18n-2) and [here](https://github.com/jeresig/i18n-node-2)).  It's widely used and seems to be in active development.  We're going to use [this handy blogpost](http://www.drzon.net/i18n-for-node-express/) as a start. Essentially, this will involve us finding all the strings in the app that need to be translated and marking them as needing translation. We'll have JSON files with the string keys and translated values -- one JSON file per language.  Then we'll add links to the homepage to show it in different languages.  We will _not_ try to guess their language for web site text or for future contact, as mentioned in #30.

When they choose a language, we'll set a request cookie so that we'll know what language to show all pages in for the remainder of their session.

**Comment by nttaylor** [comment]
My sense of fairness compels me to point out that this solution is the very same one recommended by @trystant on June 17. I originally thought it seemed unnecessarily "heavy duty", but now that I've worked with the module I see that it is also very appropriate for smaller projects and that he was right all along.

**Comment by kfogel** [comment]
On Oct 23, 2015 6:56 AM, "nttaylor" <notifications@github.com> wrote:
>
> My sense of fairness compels me to point out that this solution is the
very same one recommended by @trystant on June 17. I originally thought it
seemed unnecessarily "heavy duty", but now that I've worked with the module
I see that it is also very appropriate for smaller projects and that he was
right all along.

Thanks for pointing that out, and hat-tip to @trystant!

**Comment by kfogel** [comment]
What's standing between this and deployment?  I.e., what's current status?

**Comment by nttaylor** [comment]
The i18n framework is in and working, the translations to Spanish are done,
and the UI component is complete. I would have said it's ready.

**Comment by cecilia-donnelly** [comment]
@kfogel @nttaylor I think you're right.  We were working on applying it to #121 but that's a separate issue.  I'll test on demo and deploy if everything passes.

**Comment by cecilia-donnelly** [comment]
@OhMcGoo requests putting the switching widget in the upper right with no box.  He mentioned making it look more like it's floating, and @kfogel suggested trying out a button.

We agreed that we should look at what major sites do and Just Do That.  Here are cropped screenshots of the sites of some major cell phone carriers.  Mostly they have the language switcher at the top right.  Other than that, there isn't much of an emergent pattern.

Verizon: 
![verizon-language](https://cloud.githubusercontent.com/assets/1497818/11076352/e9706170-87bf-11e5-875a-6bc0fc9584ec.png)

AT&T:
![att-language](https://cloud.githubusercontent.com/assets/1497818/11076355/e973344a-87bf-11e5-90cb-c78929e645d5.png)

T-Mobile:
![t-mobile-language](https://cloud.githubusercontent.com/assets/1497818/11076354/e971059e-87bf-11e5-8213-4ea4fa6fe3b1.png)


  
Sprint has theirs at the bottom left, which made it shockingly hard to find:
![spring-language](https://cloud.githubusercontent.com/assets/1497818/11076433/54dbf780-87c0-11e5-8fe1-c7fc57c34d59.png)

So, definitely move to the top right and remove the background box.  We may need to change the color of the text, or make it bolder so that it's readable.  I do want to preserve some distinction in order to indicate that the language names are clickable.

**Comment by cecilia-donnelly** [comment]
Moved the language switcher to the top right, removed the background box, and bolded the text.  Here's a screenshot of my local version:

![screenshot from 2015-11-11 16-35-22](https://cloud.githubusercontent.com/assets/1497818/11105073/397ece4a-8892-11e5-8d4d-e809b59166b3.png)

**Comment by cecilia-donnelly** [comment]
Deployed with Spanish translation on [2015-11-16].  Future languages will have their own issues.
