### ISSUE TITLE
Add "complete" checkbox to admin interface

### ISSUE THREAD

**Issue by cecilia-donnelly** [redcross/smoke-alarm-portal#128]
Allow users to mark requests as completed, and to filter requests by complete/incomplete.

**Comment by cecilia-donnelly** [comment]
The "is completed" checkbox is a good first step to enable request administration.  When we go beyond this, though, we need to consider the full system ("cable TV installer"), including geographic groupings, a received->assigned->completed workflow, etc.  Let's check AllReady and DCSOps first, so that we can avoid duplicating effort and ensure that we're compatible with them.

**Comment by kfogel** [comment]
I propose that for now, we offer three mutually exclusive next states: "in-progress", "completed", and "canceled".  (When requests arrive, they are in state "new".)  Both "new" and "in-progress" are open states; the other two are closed states.

Justification: we will always have test requests, and we will therefore always want to be able to cancel them (just to get them out of the list of open requests).  And some requests may take a long time between acknowledgement and completion -- we want to have some way to represent that.

I'm trying to strike a balance between satisfying admin users now, at least at a basic level, and not going too far down the Cable TV Installer road before we've had time to really sit down and look at the other systems we may eventually integrate with.  This feels like the sweet spot, because it's a small number of states covering basic scenarios that we already know we have to handle, and under the hood it's all implemented with one new per-request field (`status`).

**Comment by kfogel** [comment]
I'm describing things conceptually above, btw.  If the actual labels used in the admin UI are different, that's fine, of course.

**Comment by cecilia-donnelly** [comment]
This is complete with the preliminary checkbox interface as of 18f850e.  We had also talked briefly about being able to sort and filter on status -- should that become a separate issue, or is it part of this one?

I'll switch to a select dropdown with the states ("installed," "canceled," etc) that @kfogel describes above, then put this on demo with the other admin improvements for feedback.

**Comment by kfogel** [comment]
Registering a mild worry that the select dropdown (to change a request's status) will become an annoyance to admin users if it turns out that there's one status they choose vastly more often than others -- say, "installed".  However, if that turns out to be the case, we can offer a single-click checkbox for that when the time comes.

I've started using the word "status" instead of "state" in this context, by the way, because we already have states -- as in, actual states of the United States -- in this application, and why ask for confusion?

**Comment by cecilia-donnelly** [comment]
Deployed as of [2016-01-28].
