### ISSUE TITLE
Applying filters in Admin Portal changes dates (back one day) on each click

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#132]
When searching for requests by a certain date range . . .

<img width="870" alt="before" src="https://cloud.githubusercontent.com/assets/4147733/11492677/f45b90e0-97b5-11e5-8819-3fc9384f0f49.png">

. . . clicking the 'apply filters' button changes each date back one day:

<img width="875" alt="after" src="https://cloud.githubusercontent.com/assets/4147733/11492688/0fb9ac28-97b6-11e5-943c-7f5bc57e92b0.png">

**Comment by kfogel** [comment]
Well, that's a bug.  I wonder if it's just a typical inclusive-versus-exclusive boundary problem.  In other words, that in order to *get* a search from 07/01 - 11/30 inclusive, one has to set the lower boundary at 06/30, but meanwhile the upper boundary is already inclusive and so if you want until 11:59:59pm on 11/29 you just specify 11/29.

However, even if that's the case, it's not a natural match for the user's expectations.  And anyway, someone who specifies 11/30 surely wants all requests from that day as well (e.g., up until 11:59:59pm of the named day).

But this is all speculation.  Maybe the bug is something sillier than that.  We'll take a look!  Thanks, Jim.

**Comment by cecilia-donnelly** [comment]
This was sort of a fun problem.  The solution is explained [in the first answer to this StackOverflow question](http://stackoverflow.com/questions/17855842/moment-js-utc-gives-wrong-date).

The longer explanation is that we do two things when a user chooses a date to search on.  First, we search on that date, and second we display it next to the "datepicker" in italics, so that users can see what they searched on.  The problem was arriving in our display step.  With this bug, you could see that the date in the query string in the URL was correct, but the _displayed_ date was one day behind.  Then, if the user searched again, the new displayed date would be passed and the date before _that_ would be displayed.

The displayed date was losing one day because the "moment" library was using the wrong time zone, as explained in that StackOverflow link.  Essentially, we converted a date to a timestamp (in order to compare it to some other values) but when we converted it back, the timestamp used a different timezone and so the new date was wrong.

My fix just makes sure that we're keeping the timezone consistent, so the date will remain correct.

**Comment by OhMcGoo** [comment]
I’m glad I could provide you a little enjoyment!
