### ISSUE TITLE
Include status field in CSV Export

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#245]
Include the **status** field in CSV Exports.

<img width="1280" alt="getasmokealarm csv export" src="https://user-images.githubusercontent.com/4147733/39664344-761ea738-5047-11e8-8440-c26b6102142a.png">

**Comment by kfogel** [comment]
Just noting that @OhMcGoo is going to look at this issue again before we start on it.

**Comment by kfogel** [comment]
Just FYI, I verified today that this bug is still present.

The fields in a CSV export right now are:

    - id
    - name
    - address
    - city
    - state
    - zip
    - phone
    - email
    - date created
    - date updated
    - county
    - chapter
    - region
    - source
    - count duplicates

Also: what is that last "count duplicates" column about?   Out of the 13620 smoke alarm requests currently in the database, that field is "0" for 13557 of them.  (Out of the 63 non-zero values, 57 are "1", 4 are "2", 1 is "3" and 1 is "4".  Go figure.)

**Comment by frankduncan** [comment]
Count duplicates is for when someone makes a second request for a specific address.  Instead of writing a new row, we add to the duplicates table and dump on the same messaging to the end user.
