### ISSUE TITLE
After a Dakotas user submitted a text request, an incomplete "Sorry . . ." message was returned

### ISSUE THREAD

**Issue by OhMcGoo** [redcross/smoke-alarm-portal#287]
Summer DeJong of the Dakotas Region submitted a test smoke alarm request by text message. After completing the four entries, she received the following message rather than a confirmation:

![Text Request Error](https://user-images.githubusercontent.com/4147733/66245048-fd5fa280-e6d0-11e9-8e11-f350ca19069f.PNG)

Note that the request data was successfully captured by the application as NDSD-20-00980.

**Comment by kfogel** [comment]
Talking with @frankduncan about it now; more in a bit.

**Comment by frankduncan** [comment]
So, bad news first.  SMS smoke alarms have been failing in this way since we deployed the region changes in early March.  The code is failing on a defunct set of code that I removed from the web path, but missed removing from the sms path.  The weird text message relating to county has to do with the object changes I made.

Good news is that they were going to the DB, so that means they were potentially getting worked on, and things were getting resolved.

Bad news last.  I have no way to actually test a fix for this in development leaving us with two options: make code changes in prod and re-submit texts for me (I made one to verify the issue was global), or spend some time figuring out how to execute the sms path in development.

**Comment by frankduncan** [comment]
Further comment to note we don't really have any tests, nor any smoke test checklist for this kind of stuff.  We should make one at some point.

**Comment by frankduncan** [comment]
@OhMcGoo I think at this point we need to figure out how we want to test texts.  I don't know anything about the twilio setup, or whether we have another number we can register?

**Comment by kfogel** [comment]
This was fixed and pushed to production on October 9th, just FYI.  My apologies for not updating the ticket here at the time!
