### ISSUE TITLE
Input field for phone number is now too narrow.

### ISSUE THREAD

**Issue by kfogel** [redcross/smoke-alarm-portal#97]
Since we went back to the side-wing layout and re-squished the input fields, the phone-number field is now too small.  See attached screenshot: the number gets cut off a bit.

Maybe the solution is to make the side panels narrower, so we can widen the input area by one Boostrap-y notch?  (As opposed to robbing email to pay phone number.)  Not sure what the best solution.  But we ought to fit phone numbers, since they're data of more or less known width.

![screenshot from 2015-08-04 02-57-28](https://cloud.githubusercontent.com/assets/401111/9055944/eb25bdca-3a54-11e5-9c64-f971d9ca4738.png)

**Comment by nttaylor** [comment]
If we were to squeeze the text blocks in order to widen the fields (including phone #), the text blocks would get even taller, and since they're already too tall compared to the height of the form.

OTOH, the text as it is now could be edited / moved around. The "please note" text in the left-hand block talks about availability and so does the bottom block. Should everything related to availability be in the bottom block? This would reduce the height of the left-hand block, which would look nice, but I guess that's not our call to make.

Under the circumstances I'm in favor of "robbing email to pay phone number": The email field is short enough that there will already be many email addresses that won't fit, so maybe we should squeeze it even more so that all phone numbers will fit.

Thoughts everyone?

**Comment by cecilia-donnelly** [comment]
We could always put email and phone number on separate lines again.  That would make the form a little taller, too, so that it would match up better with the text blocks.

**Comment by kfogel** [comment]
This got fixed as part of the issue #94 changes.  Closing.
