### ISSUE TITLE
Region name for Requests admin is currently contained in the address_2 column

### ISSUE THREAD

**Issue by trystant** [redcross/smoke-alarm-portal#99]
in the process of fulfilling #82, I placed the region_display_name for a region (as shown in `config/recipients.json.tmpl`) in the address_2 property of the returning Request object in `getResults()`. Ultimately, this should be in non database backed property of the object and the address_2 column should be removed from the system.

The code in question is in `views/admin/requests/index.js`.

**Comment by kfogel** [comment]
Two questions, only the first of which is directly related to this issue:

1. Isn't this just a matter of changing the `address_2` column (i.e., "property") to `rc_region`?  That is, the column is currently holding the identifier for the Red Cross region.  The only problem is, the column has an inaccurate name -- it's called `address_2`.  So, if we change its name to `rc_region`, the problem is fixed, no?

2. When we store the RC Region associated with a given request, why are we storing the region's display name rather than its internal code name?  The whole point of internal identifiers is to be the thing that's stored in the database.  This is exactly the same phenomenon as why, say, a User record (in a system that has user records) has a unique identifying user-number associated with it (a primary key for that user, basically), so that if the user's name changes -- say, to add a "Ms." or to fix a typo or whatever -- that doesn't change the identity of the underlying record.  I realize that this is a question you brought up before, in issue #82 I think, and I didn't say anything at the time -- I'll go raise it there.

**Comment by trystant** [comment]
1. @kfogel calling it rc_region would absolve that particular issue. We'll then have the ID of the region as well as the display name associated with the model. The best solution (IMO) is to explicitly add the region_display_name to the SelectedCounties table in the database and remove it from the config file. Regional mailing information can be retrieved from the DB when the region is selected.

2. When the region is found and stored, the id is stored in as an association and available as `Request.SelectedCounty`. The only reason we need to make another call is because the display_name is not currently in the SelectedCounties table.

I hope this helps.

**Comment by kfogel** [comment]
I agree about (1) above.  So you're saying that right now *both* the rc_region code name and the region display name are stored with the request, the latter essentially as a cache to make it easier for us to produce the display name for showing to the user in, e.g., admin section reports?

**Comment by kfogel** [comment]
This has been fixed for a while now.
